---
- name: vagrant playbook
  hosts: all

- include: omekaplay/playbook.yml
- include: dotfiles/playbook.yml
- include: ansible-playbooks/apache.yml
- include: ansible-playbooks/node.yml
- include: ansible-playbooks/rvm-ruby.yml
- include: ansible-playbooks/solr.yml
- include: ansible-playbooks/other.yml
- include: ansible-playbooks/ag.yml
